name: Sincronizar Bibliotecas
on:
  schedule:
    - cron: '0 0 * * *' # Se ejecuta una vez al día a medianoche
  workflow_dispatch:      # Permite ejecutarlo manualmente con un botón

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependencias
        run: pip install requests beautifulsoup4

      - name: Ejecutar Scripts de Datos
        run: |
          python scripts/update_anilist.py
          python scripts/update_games.py

      - name: Guardar cambios en el repositorio
        run: |
          git config --global user.name "Shadorossa-Bot"
          git config --global user.email "bot@github.com"
          git add data/*.json
          git commit -m "Sincronización automática: AniList y Backloggd" || exit 0
          git push